# ~/wordpress_template/.lando.yml - Version 17

name: wp-template-app # IMPORTANT: à changer pour chaque projet

recipe: wordpress
config:
  webroot: .
  php: '8.1'
  database: mysql:8.0

# On définit une commande personnalisée qui accepte des arguments
tooling:
  install:
    service: appserver
    description: "Finalise l'installation WP. USAGE: lando install -- --url=VOTRE_URL"
    cmd:
      # $@ passe tous les arguments supplémentaires au script
      - /app/scripts/init.sh
      - $@
  wp:
    service: appserver