# ~/wordpress_template/.lando.yml

name: wp-template-app # IMPORTANT: to be changed for each project

recipe: wordpress
config:
  # The web server will point to the "app" subdirectory.
  webroot: app
  php: '8.1'
  database: mysql:8.0

# Define our custom installation command
tooling:
  install:
    service: appserver
    description: "Finalizes the WP installation. USAGE: lando install -- --url=YOUR_URL"
    cmd:
      # The script is run from the project root, so we use an absolute path.
      - /app/scripts/init.sh
      - $@
  wp:
    service: appserver
    # Tell WP-CLI where the WordPress installation is located.
    cmd: /usr/local/bin/wp --path=/app/app